import { getPayrunDetails, updatePayrunStatus } from '../../../../../actions/payroll';
import { distributePayslips } from '../../../../../actions/distribution';
import DownloadPayslipButton from '../../../components/DownloadPayslipButton';

export default async function PayrunDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const { payrun, payslips } = await getPayrunDetails(id);
  if (!payrun) return <div className="p-8">Payroll batch not found.</div>;
  return <div className="space-y-6"><div className="rounded-2xl border border-slate-200 p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs tracking-[.2em] text-violet-300">PAYROLL BATCH</p><h1 className="mt-1 text-3xl font-bold">{payrun.name}</h1><p className="mt-2 text-sm text-slate-400">{payrun.structure_name} | {payrun.period_start} to {payrun.period_end}</p></div><form action={async()=>{'use server';await distributePayslips(id)}}><button className="rounded-lg border border-violet-400/50 px-4 py-2 text-sm font-semibold text-violet-200">Send approved payslips</button></form></div><p className="mt-4 text-sm text-slate-300"><b>Validate</b> means this payslip was reviewed and approved. <b>Paid</b> means payment has actually been released. Process payslips individually so exceptions do not block the whole batch.</p></div><div className="rounded-2xl border border-slate-200 overflow-hidden"><table className="w-full text-left"><thead><tr className="text-xs text-slate-400"><th className="p-4">EMPLOYEE</th><th>GROSS</th><th>DEDUCTIONS</th><th>NET</th><th>STATUS</th><th className="p-4">ACTION</th></tr></thead><tbody>{payslips.map((p:any)=><tr key={p.id} className="border-t border-slate-200"><td className="p-4 font-semibold">{p.first_name} {p.last_name}</td><td>${Number(p.gross_salary).toFixed(2)}</td><td>${Number(p.deductions).toFixed(2)}</td><td className="font-bold text-emerald-300">${Number(p.net_salary).toFixed(2)}</td><td>{p.status}</td><td className="p-3 flex gap-2"><DownloadPayslipButton payslip={p}/>{p.status === 'Computed' && <form action={async()=>{'use server';await updatePayrunStatus(id,'Validated',[p.id])}}><button className="rounded-lg bg-violet-600 px-3 py-2 text-xs font-bold">Validate</button></form>}{p.status === 'Validated' && <form action={async()=>{'use server';await updatePayrunStatus(id,'Paid',[p.id])}}><button className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold">Mark paid</button></form>}{p.status === 'Paid' && <span className="text-xs text-emerald-300">Payment complete</span>}</td></tr>)}</tbody></table></div></div>;
}
